# Generated by Django 5.2 on 2025-04-16 18:27

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Company',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=255)),
                ('slug', models.SlugField()),
            ],
        ),
        migrations.CreateModel(
            name='Department',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=255)),
                ('slug', models.SlugField()),
            ],
        ),
        migrations.CreateModel(
            name='Result',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=255)),
                ('slug', models.SlugField()),
            ],
        ),
        migrations.CreateModel(
            name='Status',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=255)),
                ('slug', models.SlugField()),
            ],
        ),
        migrations.CreateModel(
            name='Job',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=255)),
                ('location', models.CharField(max_length=255)),
                ('responsiblities', models.TextField(max_length=1000)),
                ('qualification', models.TextField(max_length=1000)),
                ('nice_to_haves', models.TextField(max_length=1000)),
                ('end_date', models.DateTimeField()),
                ('company', models.ForeignKey(null=None, on_delete=django.db.models.deletion.CASCADE, to='APIBackend.company')),
                ('department', models.ForeignKey(null=None, on_delete=django.db.models.deletion.CASCADE, to='APIBackend.department')),
                ('recruiter', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='recruiter', to=settings.AUTH_USER_MODEL)),
            ],
        ),
        migrations.CreateModel(
            name='Application',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=255)),
                ('email', models.EmailField(max_length=254)),
                ('residence', models.CharField(max_length=255)),
                ('cover_letter', models.TextField(max_length=1000)),
                ('user', models.ForeignKey(null=None, on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
                ('job', models.ForeignKey(null=None, on_delete=django.db.models.deletion.CASCADE, to='APIBackend.job')),
                ('status', models.ForeignKey(default=1, null=None, on_delete=django.db.models.deletion.CASCADE, to='APIBackend.status')),
            ],
            options={
                'unique_together': {('user', 'job')},
            },
        ),
        migrations.CreateModel(
            name='Interview',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('date', models.DateTimeField()),
                ('application', models.ForeignKey(null=None, on_delete=django.db.models.deletion.CASCADE, to='APIBackend.application')),
                ('result', models.ForeignKey(default=1, null=None, on_delete=django.db.models.deletion.CASCADE, to='APIBackend.result')),
            ],
        ),
    ]
