# Generated by Django 5.2 on 2025-04-27 08:34

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('APIBackend', '0002_alter_interview_date_alter_job_unique_together_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='application',
            name='match_score',
            field=models.FloatField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='application',
            name='resume',
            field=models.FileField(blank=True, null=True, upload_to='resumes/'),
        ),
    ]
