# Generated by Django 5.2 on 2025-04-27 13:14

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('APIBackend', '0003_application_match_score_application_resume'),
    ]

    operations = [
        migrations.AddField(
            model_name='interview',
            name='meeting_id',
            field=models.CharField(blank=True, max_length=50, null=True),
        ),
        migrations.AddField(
            model_name='interview',
            name='meeting_link',
            field=models.CharField(blank=True, max_length=255, null=True),
        ),
    ]
