# Generated by Django 5.2 on 2025-04-27 19:14

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('APIBackend', '0004_interview_meeting_id_interview_meeting_link'),
    ]

    operations = [
        migrations.AddField(
            model_name='interview',
            name='analysis_data',
            field=models.JSONField(blank=True, null=True),
        ),
    ]
