# Generated by Django 5.2 on 2025-04-28 11:58

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('APIBackend', '0005_interview_analysis_data'),
    ]

    operations = [
        migrations.RenameField(
            model_name='interview',
            old_name='meeting_link',
            new_name='external_meeting_link',
        ),
        migrations.RemoveField(
            model_name='interview',
            name='meeting_id',
        ),
        migrations.AddField(
            model_name='interview',
            name='interview_video',
            field=models.FileField(blank=True, null=True, upload_to='interviews/'),
        ),
    ]
