# Generated by Django 5.2 on 2025-04-29 04:39

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('APIBackend', '0006_rename_meeting_link_interview_external_meeting_link_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='interview',
            name='interview_questions',
            field=models.JSONField(blank=True, null=True),
        ),
        migrations.AlterUniqueTogether(
            name='interview',
            unique_together={('application',)},
        ),
    ]
