# Generated by Django 5.2 on 2025-04-29 08:47

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('APIBackend', '0007_interview_interview_questions_and_more'),
    ]

    operations = [
        migrations.CreateModel(
            name='EvaluationStatus',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=255)),
                ('slug', models.SlugField()),
            ],
        ),
    ]
