# Generated by Django 5.2 on 2025-04-29 09:28

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('APIBackend', '0008_evaluationstatus'),
    ]

    operations = [
        migrations.CreateModel(
            name='PredictedCandidate',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('evaluation_score', models.FloatField(blank=True, null=True)),
                ('evaluation_data', models.JSONField(blank=True, null=True)),
                ('interview', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='predicted_candidate', to='APIBackend.interview')),
                ('status', models.ForeignKey(default=1, on_delete=django.db.models.deletion.CASCADE, to='APIBackend.evaluationstatus')),
            ],
        ),
    ]
