# Generated by Django 5.2 on 2025-07-24 07:32

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('APIBackend', '0009_predictedcandidate'),
    ]

    operations = [
        migrations.AddField(
            model_name='company',
            name='logo',
            field=models.ImageField(default='logos/building-2.png', upload_to='logos/'),
        ),
    ]
