# Generated by Django 5.2 on 2025-07-25 12:35

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('APIBackend', '0010_company_logo'),
    ]

    operations = [
        migrations.DeleteModel(
            name='RecruiterRequest',
        ),
    ]
